//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegracionPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la_Carpeta donde se Cargarán las Ordenes de Compra a Procesadar.
        /// </summary>
        internal static string Configuraciones_SetOaProcesarPath_Seleccione_la_Carpeta_donde_se_Cargarán_las_Ordenes_de_Compra_a_Procesadar {
            get {
                return ResourceManager.GetString("Configuraciones_SetOaProcesarPath_Seleccione_la_Carpeta_donde_se_Cargarán_las_Ord" +
                        "enes_de_Compra_a_Procesadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la Carpeta donde se almacenaran las Ordenes de Compra Procesadas.
        /// </summary>
        internal static string Configuraciones_SetOCProcesadasFolder_Seleccione_la_Carpeta_donde_se_almacenaran_las_Ordenes_de_Compra_Procesadas {
            get {
                return ResourceManager.GetString("Configuraciones_SetOCProcesadasFolder_Seleccione_la_Carpeta_donde_se_almacenaran_" +
                        "las_Ordenes_de_Compra_Procesadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la Carpeta donde se Guardaran los Archivos del Log.
        /// </summary>
        internal static string Configuraciones_SetOutputFolder_Seleccione_la_Carpeta_donde_se_Guardaran_los_Archivos_del_Log {
            get {
                return ResourceManager.GetString("Configuraciones_SetOutputFolder_Seleccione_la_Carpeta_donde_se_Guardaran_los_Arch" +
                        "ivos_del_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Formato del PDF no ha sido reconocido....
        /// </summary>
        internal static string MainWindow_button_Click_El_Formato_del_PDF_no_ha_sido_reconocido___ {
            get {
                return ResourceManager.GetString("MainWindow_button_Click_El_Formato_del_PDF_no_ha_sido_reconocido___", resourceCulture);
            }
        }
    }
}
